### ISSUE TITLE
[FBX]There are bugs when importing certain FBX models exported from Blender.

### ISSUE THREAD

**Issue by VTui22** [meta4d-me/AssetPipeline#234]
![image](https://github.com/CatDogEngine/AssetPipeline/assets/106135221/3becfb26-b58b-473f-9e30-85e2d7526c28)
Here, When Node is RootNode,pParentNode should be nullptr,but it will enter the if statement condition

**Comment by T-rvw** [comment]
Please attach the test fbx file to issue or upload to a repo such as TestAssets.

**Comment by VTui22** [comment]
The test file in TestAssets/BadCases/walk_from_blender

**Comment by T-rvw** [comment]
@VTui22 Have a try after `5dc22fc` fix. You can reopen this issue if still has bugs.
