### ISSUE TITLE
[Mesh] Support up to 8 color and texture coordinates

### ISSUE THREAD

**Issue by ChaoSXDemon** [meta4d-me/AssetPipeline#49]
Currently bgfx supports up to 8 color and texture coordinates per vertex. However, AssetPipeline only supports up to 4 and only 1 is encoded in the Mesh class.

**Comment by T-rvw** [comment]
@ChaoSXDemon Interesting findings. In my experience, 4 color/UV sets are enough for almost all projects.
We can improve "only 1 is encoded" when we want to use lightmap. It will use the second UV set.
Anyway, it is OK to improve when necessary.
