### ISSUE TITLE
[Math] linear algebra library

### ISSUE THREAD

**Issue by roeas** [meta4d-me/AssetPipeline#7]
Need some math functions to calculate simple vector arithmetic.

**Comment by T-rvw** [comment]
* TODO
  * Basic  
    * Matrix
    * Quaternion
  * Geometry
    * Cone
  * Intersections
  * Optimizations
    * DirectMath
    * SSE
    * ...

**Comment by T-rvw** [comment]
Here is a good reference for writing a simple template math lib : google/mathfu.
I already added matrix, quaternion after looking at its implementation.
